"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os



NAME = ['CRYtabia']
VERSION = ['0.10.0']
APP = ['main.py']
DATA_FILES = [
	'infolib.xlsx',
	'images'
]
OPTIONS = {
	"iconfile": "images/icon.icns",
	'argv_emulation': True,
	"packages": ['pandas','pygbif']
	
	}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DB_FILE = os.path.join(SCRIPT_DIR, "data/genotree_master_library.db")

if __name__=='__main__':
	setup(
	    app=APP,
	    data_files=DATA_FILES,
	    options={'py2app': OPTIONS},
	    setup_requires=['py2app'],
	)
